### ISSUE TITLE
Citation recommendation

### ISSUE THREAD

**Issue by jelber2** [natir/br#10]
Working on a pre-print using brutal rewrite and was wondering if you could recommend a citation or mainly are there others than yourself that have contributed to the work?

**Comment by natir** [comment]
With Antoine Limasset, we presented br at the SeqBim conference https://seqbim2020.sciencesconf.org/resource/page/id/4.html. Philipp Spohr worked on the other part of the presentation.

If you could link slide and repository it's could be perfect or only repository it's ok.
