### ISSUE TITLE
methods are applied in the order you specify?

### ISSUE THREAD

**Issue by jelber2** [natir/br#2]
Very interesting tool!

Can you clarify how `-m` "methods are applied in the order you specify" works? So `-m one` is different than `-m one -m two`?
for commit [a7b62da](https://github.com/natir/br/commit/a7b62dac1e1c84e8767c23440e57c1e5a81f00fc)

**Comment by natir** [comment]
Hi,

Thank for your interest, `br` implement many correction method and `-m` option allow user to choose which method are apply. `-m one` apply only `one` algorithm, `-m one -m two` apply algorithm `one` and `two`. Sorry we didn't finish publication and correction algorithm isn't well describe.

I hope I help and if you have any question please ask.

**Comment by jelber2** [comment]
That is great, thanks!
